=== spilnotaxyz/chyn/apps/www/public/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "style": {
      "type": "string",
      "enum": ["default"]
    },
    "tailwind": {
      "type": "object",
      "properties": {
        "config": {
          "type": "string"
        },
        "css": {
          "type": "string"
        },
        "baseColor": {
          "type": "string"
        },
        "cssVariables": {
          "type": "boolean"
        },
        "prefix": {
          "type": "string"
        }
      },
      "required": ["config", "css", "baseColor", "cssVariables"]
    },
    "rsc": {
      "type": "boolean"
    },
    "tsx": {
      "type": "boolean"
    },
    "aliases": {
      "type": "object",
      "properties": {
        "utils": {
          "type": "string"
        },
        "components": {
          "type": "string"
        },
        "ui": {
          "type": "string"
        }
      },
      "required": ["ui", "utils", "components"]
    }
  },
  "required": ["style", "tailwind", "rsc", "aliases"]
}

=== spilnotaxyz/chyn/packages/cli/test/fixtures/config-full/chyn-components.json
{
  "style": "default",
  "tailwind": {
    "config": "tailwind.config.ts",
    "css": "src/app/globals.css",
    "baseColor": "zinc",
    "cssVariables": true,
    "prefix": "tw-"
  },
  "rsc": false,
  "aliases": {
    "utils": "~/lib/utils",
    "components": "~/components",
    "ui": "~/components/ui"
  }
}
